# Generated by Django 3.1.2 on 2020-10-30 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LegacySite', '0002_auto_20201030_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='used',
            field=models.BooleanField(default=False),
        ),
    ]
